### ISSUE TITLE
View Transfers window

### ISSUE THREAD

**Issue by dadoprom** [nitroshare/nitroshare-desktop#103]
There should be listed a name of the file or directory which is being transfered in view transfers window...

**Comment by nathan-osman** [comment]
It is very likely that this feature will be added to the next release.

**Comment by techtonik** [comment]
Received my first file from Nitroshare and already miss this feature. )

**Comment by nathan-osman** [comment]
I'll see if I can get that feature added this week.

**Comment by techtonik** [comment]
I want to see filename to know if I should accept or skip it in https://github.com/nitroshare/nitroshare-desktop/issues/121 so if Transfer Window showed files currently in "quarantine", that could make a good experience. Like:

    filename            [Accept][Remove]
    filename            [Accept][Remove]
    filename            [Open]

**Comment by nathan-osman** [comment]
Hmm... this isn't possible using the current transfer protocol since the filename and other metadata aren't transferred until immediately before the payload. In other words, it would need to prompt for each file one-at-a-time as it is received. However, it is certainly possible to _display_ the current item being transferred.

**Comment by techtonik** [comment]
I think about `quarantine` after the file is transferred. So `Accept` here means moving from unsafe area to download destination. No need to keep pusher waiting for transfer.

**Comment by nathan-osman** [comment]
Oh, okay. Yes, that's definitely possible.

**Comment by nathan-osman** [comment]
I implemented a quarantine option as you suggested. It still needs a bit of adjustment but for the most part it works. To enable the feature, ensure the following checkbox is checked:

![quarantine](https://user-images.githubusercontent.com/1253444/27759139-15262350-5ddd-11e7-8f11-eba88d7fd16e.png)

Once enabled, you will receive a prompt when a transfer completes:

![confirm](https://user-images.githubusercontent.com/1253444/27759141-361cd95a-5ddd-11e7-86e8-f2d16bf4dcdf.png)

Clicking "yes" will move them to the correct location and clicking "no" will simply ignore the files.

**Comment by techtonik** [comment]
I'd prefer not to see popup windows, but click the icon myself to open the transfer window and accept them. Another problem with the window that there is no list of files that are going to be accepted.

**Comment by nathan-osman** [comment]
> "I'd prefer not to see popup windows, but click the icon myself to open the transfer window and accept them."

This is a hard decision to make. On the one hand, it makes sense to inform the user that a transfer has completed and must be accepted. On the other hand, I can understand how this would quickly get out of control if a large number of transfers were received at once. Perhaps the behavior can be controlled by a separate setting.

> "Another problem with the window that there is no list of files that are going to be accepted."

Yes, I plan to have that added very soon.

**Comment by nathan-osman** [comment]
Both the list of items and popup window request have been completed now.

**Comment by pflueg** [comment]
@nathan-osman : Just for clarification - is the client on the receiver side blocking the transfer until the receiver accepts the files or are the files already transferred before the prompt pops up?

It should ask *before* it accepts the transfer - otherwise anybody will be able to fill up the drive of the receiver regardless of the prompt.

Thanks alot!
