### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by derek3x** [nitroshare/nitroshare-desktop#11]
Is it possible to put in an option to use the command line to send a file?  I would like to automatically send files and if there was a command line option I could create a quick script to watch a folder for changes and then they will be automatically transferred using a command line option in nitroshare .

For my reasons or other peoples reasons; I am sure people would like a quick and dirty command line option.

If this exists, I could not find the documentation.

**Comment by nathan-osman** [comment]
This is a planned feature. Once the RPC interface is complete, it will also be possible to send files using a tool such as cURL.

**Comment by rapgro** [comment]
There's notify-send, used for the kservicemenu extension.
