### ISSUE TITLE
macOS: system menu icon does not fade on inactive desktops

### ISSUE THREAD

**Issue by waldyrious** [nitroshare/nitroshare-desktop#111]
The icon should become slightly faded-out on a system menu that is displayed in a desktop/monitor that doesn't currently have focus. Here's how the current icon looks next to other icons that implement this behavior:

<img width="346" alt="screen shot 2017-03-23 at 18 43 46" src="https://cloud.githubusercontent.com/assets/478237/24264635/fff13ee8-0ff8-11e7-9602-ad445c19e63c.png">

**Comment by nathan-osman** [comment]
This sounds like a Qt bug, but I'll have to investigate further. I only recently obtained the necessary adapter to connect a second monitor to my testing Mac.

**Comment by waldyrious** [comment]
Let me know if there's anything I can help with :)

**Comment by mateosalta** [comment]
This looks relavant, https://stackoverflow.com/a/41903980/1487176

Looks like they have a icon file that can change with a few settings?

**Comment by nathan-osman** [comment]
I made the change to call `QIcon::setIsMask()`. If someone can grab the DMG from [the CI server](https://ci.quickmediasolutions.com/job/nitroshare/toolchain=macos&&x86_64&&clang/) and try it out, that would be great.

**Comment by nathan-osman** [comment]
Hmm... the icon needs to have a transparent center.

**Comment by mateosalta** [comment]
I think it will be good once you have it transparent - it changes with the theme as well - I have not tried the second screen, but I bet that is similar and will change with the other icons, I can confirm it is changing color with  
![screen shot 2017-07-06 at 8 59 16 pm](https://user-images.githubusercontent.com/1965279/27940150-a1451a3e-628e-11e7-8143-7f622e7c463f.png)

![screen shot 2017-07-06 at 9 00 04 pm](https://user-images.githubusercontent.com/1965279/27940153-a6a1c342-628e-11e7-8f39-b3527848bb33.png)
![screen shot 2017-07-06 at 9 00 29 pm](https://user-images.githubusercontent.com/1965279/27940158-ab627f84-628e-11e7-86c1-156953766c7a.png)
