### ISSUE TITLE
Transfer time

### ISSUE THREAD

**Issue by mehalom** [nitroshare/nitroshare-desktop#113]
If the program showed remaining time for each transfer, it would be very useful.

**Comment by nathan-osman** [comment]
This can be implemented as soon as #161 is complete (hopefully within the next day or two).

**Comment by nathan-osman** [comment]
This is now implemented:

![screenshot_20180110_164157](https://user-images.githubusercontent.com/1253444/34803019-cf83f05c-f625-11e7-8b86-8d7fb09a331a.png)
