### ISSUE TITLE
0.3.4 latest build fails after install

### ISSUE THREAD

**Issue by techtonik** [nitroshare/nitroshare-desktop#117]
![image](https://cloud.githubusercontent.com/assets/515889/26717892/b623f492-4787-11e7-9d99-63f4d2e5543e.png)

nitroshare-0.3.4-windows-x86.exe
SHA1: 1854efc0e38fb9879bf93d8d8c793c170a736ab9

From https://ci.quickmediasolutions.com/job/nitroshare/toolchain=windows&&x86&&msvc2015/lastSuccessfulBuild/artifact/build/nitroshare-0.3.4-windows-x86.exe (which will most likely change).

**Comment by techtonik** [comment]
It appears that application still works. At least menus in systray.

**Comment by nathan-osman** [comment]
That's odd. It appears the OpenSSL libraries aren't being included in the package.

**Comment by nathan-osman** [comment]
This _appears_ to be limited to the Windows platform since Qt on macOS either uses Secure Transport (the native API) or the bundled version of OpenSSL.
