### ISSUE TITLE
Nitroshare doesn't start automatically on boot/logon (Ubuntu 16.04)

### ISSUE THREAD

**Issue by peterkahl** [nitroshare/nitroshare-desktop#118]
Where is the problem? Shouldn't it start automatically?
Because I don't see the Nitro icon, I can't access/change the settings.

**Comment by nathan-osman** [comment]
It should start automatically if you go to the settings dialog and enable the corresponding option. If this doesn't work, then something is definitely malfunctioning.

**Comment by peterkahl** [comment]
Yes, I figured that out myself. The problem is that I can't see the tray icon in XFCE and can't enable the autostart option.

**Comment by nathan-osman** [comment]
Hmmm... I thought I had the icon working in XFCE but apparently it needs more work.

**Comment by peterkahl** [comment]
Got the XFCE thing working and the Nitro icon now shows!

Thanks!
