### ISSUE TITLE
Ubuntu 16.04: using IPv6 or IPv4

### ISSUE THREAD

**Issue by peterkahl** [nitroshare/nitroshare-desktop#119]
Nitro just chose IPv6 and I have no way to force Nitro to use IPv4 instead.

Or, why can't Nitro use both IPv4 and IPv6?

**Comment by nathan-osman** [comment]
Good question. I can see the need for adding an option to limit transfers to a specific protocol. By default NitroShare just uses the first address it receives.

**Comment by peterkahl** [comment]
On my network, the eth interface runs dual stack IPv4 and 6.
On my wifi interface only IPv4.
So I fear that I will not be able to use Nitroshare on my wifi-connected devices because the wired network is IPv6.

**Comment by nathan-osman** [comment]
The mDNS resolver should be smart enough to use whatever addresses are available. If one interface only has an IPv4 address, it should be able to use it without problems, even if other interfaces provide an IPv6 address.

**Comment by peterkahl** [comment]
Sublime!

**Comment by peterkahl** [comment]
As expected, I have now verified that some of my devices cannot connect to each other because one is using IPv4 and the other IPv6.
Looking forward to the new version of Nitro.

**Comment by nathan-osman** [comment]
If you would like to give the new version a try, you can grab Windows and macOS builds [here](https://ci.quickmediasolutions.com/job/nitroshare/). [The dev PPA](https://launchpad.net/~george-edison55/+archive/ubuntu/nitroshare-dev) can be used for installing on Ubuntu 16.04.

**Comment by peterkahl** [comment]
Great! Will give it a try and report back. Thanks!

**Comment by peterkahl** [comment]
It may take me a few more days to fully test the newest version, but meanwhile, I want to report on some minor difficulties with the Ubuntu installation.
After adding the PPA and running the dist-upgrade, the system complains:
```
Preparing to unpack .../libqhttpengine1_1.0.0+dfsg1-0~201705161900~ubuntu16.04.1_amd64.deb ...
Unpacking libqhttpengine1 (1.0.0+dfsg1-0~201705161900~ubuntu16.04.1) ...
dpkg: error processing archive /var/cache/apt/archives/libqhttpengine1_1.0.0+dfsg1-0~201705161900~ubuntu16.04.1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libQHttpEngine.so.1.0.0', which is also in package libqhttpengine0 1.0.0+dfsg1-0~201702232227~ubuntu16.04.1
.... [truncated]
Errors were encountered while processing:
 /var/cache/apt/archives/libqhttpengine1_1.0.0+dfsg1-0~201705161900~ubuntu16.04.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
How I got this resolved was:
```
apt remove nitroshare
apt autoremove
apt install nitroshare
```
Will report more in a few days.

**Comment by nathan-osman** [comment]
Thanks for the heads up. I'll investigate that error.

**Comment by peterkahl** [comment]
Works across IPv6 & IPv4 now! Sublime! Thanks!

**Comment by nathan-osman** [comment]
Great! Glad to hear that.
