### ISSUE TITLE
Right/Left click on Nitroshare tray icon?

### ISSUE THREAD

**Issue by rogovsky** [nitroshare/nitroshare-desktop#122]
Just an idea for next release implementation:

1. Right click on the icon opens context menu as for now.
2. Left click on the icon opens the "Transfers" window and next one close this window. So, in principle, double-click will do rise-down "Transfers" window.

**Comment by nathan-osman** [comment]
Which platform is this on? Windows? macOS? Linux?

**Comment by rogovsky** [comment]
On my Linux Mint 18.1 right or left cick (both) opens context menu with "Settings", "About" ...

**Comment by nathan-osman** [comment]
Unfortunately, due to the way the tray icon is implemented in Qt on Linux, I don't really have control over how the application responds to the different types of clicks.
