### ISSUE TITLE
Add menu option "Show transfered files in Folder"

### ISSUE THREAD

**Issue by MarTinazzI** [nitroshare/nitroshare-desktop#125]
Need a button in View Transfers and a option to "Show transfered files Folder"

**Comment by nathan-osman** [comment]
Good idea. I've added a button to the transfer window:

![2017-07-25 13_16_33-transferwindow cpp master - nitroshare - qt creator](https://user-images.githubusercontent.com/1253444/28591726-953302ea-713b-11e7-8b51-bad7dc74ad3d.png)
