### ISSUE TITLE
Message/popup/prompt instead of just plain blocking

### ISSUE THREAD

**Issue by Cornflakes91** [nitroshare/nitroshare-desktop#132]
what it says on the tin.
would be nice if there was some kind of prompt or anything that shows a receiving client that someone wants to send a file with the possibility to approve or deny, instead of just plainly blocking all incoming transfers. (maybe with some optional "allow always from this client" for trusted clients, eventually in combinations with the cert system)

**Comment by nathan-osman** [comment]
Are you looking for something like this?

https://github.com/nitroshare/nitroshare-desktop/issues/103#issuecomment-312410255

This feature was recently added and has not made it into a stable release yet.

**Comment by Cornflakes91** [comment]
Yep, thats what im asking for :D
(Did only check the current stable download and the github issues and didnt see it)
