### ISSUE TITLE
send directory using explorer extension

### ISSUE THREAD

**Issue by greatwroth** [nitroshare/nitroshare-desktop#133]
I see the new explorer extension can send files but not folders. Are there any plans to add this feature?
v0.3.4 x86_64 build 89 on Windows 10 Pro x64

**Comment by nathan-osman** [comment]
Hmm... it should be able to send folders too. Let me see if I can reproduce this issue on my Win10 virtual machine.

**Comment by nathan-osman** [comment]
Yup, I can reproduce this, although it does work if you also select a file in addition to a folder. I will see if this can easily be fixed.

**Comment by greatwroth** [comment]
Take your time, and I'd be happy to try a fixed build whenever it's ready.

**Comment by nathan-osman** [comment]
I think I've fixed this - I'll test on my VM.

**Comment by nathan-osman** [comment]
Yup, appears to be fixed now - you can test it here: https://ci.quickmediasolutions.com/job/nitroshare/toolchain=windows&&x86_64&&msvc2015/lastSuccessfulBuild/artifact/build/nitroshare-0.3.4-windows-x86_64.exe
