### ISSUE TITLE
Display progress in Unity launcher icon

### ISSUE THREAD

**Issue by nathan-osman** [nitroshare/nitroshare-desktop#14]
When running in Ubuntu under Unity, it would be cool if the progress of the current transfer was displayed in the corresponding launcher icon.

**Comment by DaaX** [comment]
Hi, this is an important feature to add to a future version. I agree on this one.

**Comment by nathan-osman** [comment]
I'm going to assign this to the 0.3.1 milestone then (the one immediately following the 0.3 release).
