### ISSUE TITLE
Implement CLI client

### ISSUE THREAD

**Issue by nathan-osman** [nitroshare/nitroshare-desktop#143]
The CLI client connects to the API (provided by the api plugin) and issues requests based on the arguments it receives.

In order to be useful, the API needs to provide a "directory" of actions that the client can query and display to the user with a brief description. It might also be wise to have only specific actions exposed via the API using another property. (The "ui" property should probably be renamed to "menu" or something.

**Comment by techtonik** [comment]
https://github.com/OAI/OpenAPI-Specification ?

**Comment by nathan-osman** [comment]
That's definitely a possibility. I'll see how the time goes as we approach the release (which is not even close to being ready yet).

**Comment by techtonik** [comment]
Does it provide a list of actions?

**Comment by techtonik** [comment]
It looks like code fails if no action is supplied, but there are no list of actions displayed in command line help/

**Comment by nathan-osman** [comment]
Good idea. I'll open a new bug for that.

https://github.com/nitroshare/nitroshare-desktop/issues/164

**Comment by nathan-osman** [comment]
In the meantime, if you right-click the tray icon and select "Show Developer Window..." you can see a list of actions and their parameters as well as try them out.

**Comment by techtonik** [comment]
Unfortunately, there is no tray icon in Fedora. :(

I have no idea how to interact with nitroshare running in background. Making it both GUI and CLI would help a lot, especially with debugging discovery problems.
