### ISSUE TITLE
Nitroshare icon not showing up when started from terminal

### ISSUE THREAD

**Issue by FabrizioMarana** [nitroshare/nitroshare-desktop#16]
OS: 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Symptoms:
Both in `xterm` and `gnome-terminal`, running under vanilla Unity, `nitroshare &` does start the nitroshare application, but no icon is drawn in the menu bar.

![nitroshare terminal bug](https://cloud.githubusercontent.com/assets/8290759/6085445/b6e5d3e2-ae4a-11e4-9b06-9dead32c216d.png)

**Comment by nathan-osman** [comment]
Hmmm... sounds like `XDG_CURRENT_DESKTOP` isn't set from the terminal (this is what the application uses to determine what desktop environment it is running under.

What happens if you open a terminal and run:

    echo $XDG_CURRENT_DESKTOP

**Comment by FabrizioMarana** [comment]
Same-same
> $ echo $XDG_CURRENT_DESKTOP
> Unity
> fab-user@fab-ux:~
> $ nitroshare &
> [2] 11896
> fab-user@fab-ux:~
> $ jobs
> [1]-  Running                 gedit /usr/share/X11/xkb/symbols/bg &
> [2]+  Running                 nitroshare &

> fab-root@fab-ux:~
> $ pgrep nitroshare
> 11896

**Comment by nathan-osman** [comment]
Now that _is_ weird. I tried to reproduce this, but have been unable to do so on both my desktop and VM (both running 14.10).

**Comment by FabrizioMarana** [comment]
I also run X11-forwarding... Next test: admin user and X11 forwarding
turned off...

**Comment by FabrizioMarana** [comment]
Culprit found: the X11-forwarding.  It works if I remove:
> export $(dbus-launch)
from my
> /etc/bash.bashrc

(but then I can't run any X11 programs under another user...)

**Comment by nathan-osman** [comment]
Okay, so this isn't really a bug with NitroShare but rather an issue with the appropriate environment variable being set. For the record, the application will still attempt to display a system tray icon - it will just use the `QSystemTrayIcon` class, which is broken under Qt5 in Unity. There's really not much I can do in this scenario short of providing some sort of override flag.

**Comment by FabrizioMarana** [comment]
I'm cool with that...  It's not like you'll have 100s of users running like that anyway.  And people using X11 forwarding know that it breaks some stuff.  E.g. gedit doesn't display any menus in the menu bar...  I'm a good tester anyway: If something doesn't work, I can find back why it doesn't most of the time; sometimes it just takes a few hours.)  ;-)
