### ISSUE TITLE
Retry button for restarting a transfer that failed

### ISSUE THREAD

**Issue by nathan-osman** [nitroshare/nitroshare-desktop#17]
Currently, if a transfer fails for some reason (poor network connection, etc.) the transfer cannot be restarted without being recreated from scratch. (The user must select the files and device again.) A retry button would remember the files and attempt to resend them to the same device.

**Comment by FabrizioMarana** [comment]
Erm, just tried so tend a 20 GB directory, went out for pizza, one of the machines hibernated at 83% of the transfer, and the retry button just resends everything from scratch.

Can we have a `Resume` button instead of a `Retry` one?  :-)

**Comment by nathan-osman** [comment]
Yes, #1 would actually be pretty simple to implement. I'll see what I can do.

**Comment by nathan-osman** [comment]
For organization's sake, I've opened a new bug for this: #76.
