### ISSUE TITLE
False Positive Trojan (Virus Total)

### ISSUE THREAD

**Issue by antuketot76** [nitroshare/nitroshare-desktop#193]
Please check with virustotal scanner detect this as trojan (Trojan.Win32.Nimnul!O)
Platform - Window 64Bit
Website - [(Official)](https://nitroshare.net/#)
VirusTotal - [Scan Result](https://www.virustotal.com/#/file/0816aa1147f66d09b5af96170ab34361516a58a98d98470025b285ade71ca358/detection)
Detected By - CMC (Trojan.Win32.Nimnul!O)
SHA-256 - 0816aa1147f66d09b5af96170ab34361516a58a98d98470025b285ade71ca358
File Name - nitroshare-0.3.4-windows-x86_64.exe
File Size - 8.88 MB
Last Analysis - 2018-04-27 18:25:51 UTC

![image](https://user-images.githubusercontent.com/33280865/39379637-de9b3fe4-4a96-11e8-9ae4-61c15c0d0fc4.png)

**Comment by nathan-osman** [comment]
This is a false positive. I instructed VirusTotal to reanalyze the file and the warning disappeared.

**Comment by antuketot76** [comment]
Yeah, its cleared now.
![image](https://user-images.githubusercontent.com/33280865/39414784-9cfd488e-4c76-11e8-80da-f953a64ba2e4.png)
Thanks for fast action taken, bravo bro.
