### ISSUE TITLE
Release and package

### ISSUE THREAD

**Issue by Nek-** [nitroshare/nitroshare-desktop#20]
Hello,

I was searching for a tool like that. (actually I don't know how it looks but according to what you say it sounds good)

Too bad the last release was on 2012, building is clearly not friendly when you're searching for simplicity. Do you need help to package ? (I'm using ubuntu)

**Comment by nathan-osman** [comment]
Thanks, but we already have Debian packaging for the application. In fact, there are daily builds available on Launchpad. You can add the PPA to your system with the following command:

    sudo add-apt-repository ppa:george-edison55/nitroshare-dev

Then refresh the list of packages and install it:

    sudo apt-get update
    sudo apt-get install nitroshare
