### ISSUE TITLE
Nitroshare not in official arch linux repositories

### ISSUE THREAD

**Issue by giorgosioak** [nitroshare/nitroshare-desktop#217]
This app is so good i think its shame that it does not come as an official package.

I saw that you already provide the app in ubuntu official repos.

Why not supporting other distributions like Arch?

Doing `pacman -S nitroshare` would be great for the app to stay updated without having to do it manually through AUR.

Thank you, GI

**Comment by Webbeh** [comment]
It's not up to Nitroshare to decide what goes in the official repositories or not.

It is up to the [Trusted Users](https://wiki.archlinux.org/index.php/Trusted_Users) of ArchLinux to decide whether a package will be upgraded from [AUR](https://aur.archlinux.org/packages/nitroshare/) to `community`.

If you want to have your packages updated automatically by one command, use an [AUR Helper](https://wiki.archlinux.org/index.php/AUR_helpers). I'm using [yay](https://aur.archlinux.org/packages/yay/), for example.

**Comment by hhirsch** [comment]
@giorgosioak Can you close the issue? **Webbeh** explained why it can not be fixed by anybody working on this project.
