### ISSUE TITLE
DEB file for version 0.3.4

### ISSUE THREAD

**Issue by VladimirMikulic** [nitroshare/nitroshare-desktop#233]
This is not a bug, rather a request.
Latest .deb file version is 0.3.x, please package the new version(0.3.4) in .deb also as you did for Windows(.exe).

Thanks

**Comment by revast** [comment]
Stable PPA is sadly outdated, have compiled 0.3.4 myself: 
http://openartisthq.org/debian/bionic64/nitroshare_0.3.4-1_amd64.deb

As an alternative, you could also use [Dukto](https://software.opensuse.org/download.html?project=home:colomboem&package=dukto), but also no development any more...

**Comment by souhaiebtar** [comment]
@revast thanks  it worked just fine, can you please help me build it to ubuntu 2004 because i'm new to deb packaging, thanks anyway
