### ISSUE TITLE
Error linux mint 20 ulyana

### ISSUE THREAD

**Issue by ssamss** [nitroshare/nitroshare-desktop#259]
Good afternoon Sir

t's i possible to install niteoshare on Linux mint 20 ulyana
I have tried everything
Here are 3 ways i tried, but none is possible to works.
Can you solve this.
Please Help if it is possible 
![Screenshot from 2020-10-29 22-44-02](https://user-images.githubusercontent.com/49945065/97637139-69c6e580-1a3a-11eb-89f1-76bf84bd25b8.png)

**Comment by ssamss** [comment]
Thank in advance, I hope you will success, beacuse i googled everthing, but could not make it.

**Comment by TeamDlxx** [comment]
same issue

**Comment by ayr-ton** [comment]
Is this project still being maintained? 
It seems without updates for a while.

**Comment by ssamss** [comment]
I don't know even myself, i was also interested but there was no reponse
