### ISSUE TITLE
Prevent multiple instances from running

### ISSUE THREAD

**Issue by nathan-osman** [nitroshare/nitroshare-desktop#30]
It would be nice if NitroShare presented a warning that indicated another instance was running if that was the case. Although subsequent instances will display an error about not being able to bind to the transfer port, the application will still run.

**Comment by nathan-osman** [comment]
It should be possible to solve this and facilitate authentication with the local API at the same time by creating some sort of token upon startup that only other local applications can access. The presence of the token would suggest that another instance is already running.

**Comment by nathan-osman** [comment]
The local API should make this trivial. An additional route (something to the effect of `/ping`) can be used to see if NitroShare is running and if so, refuse to start.

**Comment by rapgro** [comment]
https://doc.qt.io/archives/qtopia4.3/qtopiadesktop/qtsingleapplication.html
https://github.com/qtproject/qt-solutions/tree/master/qtsingleapplication
