### ISSUE TITLE
file selector problem

### ISSUE THREAD

**Issue by dln949** [nitroshare/nitroshare-desktop#35]
nitroshare 0.3.0

64 bit Ubuntu 14.10 on a 64 bit computer

In nitroshare, when selecting files, I need to select some "hidden" files, but they do not show up in the file selector.  Also, none of the samba mounted shares show up.  How do I make hidden files and directories, and samba shares appear so I can select files in them?  

Thanks.

**Comment by nathan-osman** [comment]
The file selector dialog shown in the application is provided by the Qt framework. To select hidden files, right-click an empty part of the file list and select "Show hidden files".

As for Samba shares, I'm not entirely sure if it is possible to access shares mounted through Nautilus. If the SMB shares are mounted with `cifs`, you can access them directly through the filesystem.
