### ISSUE TITLE
No system tray icon on Xubuntu 14.10

### ISSUE THREAD

**Issue by jpfleury** [nitroshare/nitroshare-desktop#37]
I've installed the package `nitroshare-0.3.0-amd64.deb` on Xubuntu 14.10 64-bit.

The first time I run nitroshare, I saw the introduction window and closed it. No icon appeared in the system tray, like all subsequent tests, so I don't know how to use NitroShare.

I wonder if this is a bug related to QT 5. See this issue:

https://github.com/andrew-bibb/cmst/issues/34

It seems to be a similar problem.

**Comment by nathan-osman** [comment]
This is a known issue and will be addressed in the next release. In the meantime, you can force NitroShare to use an AppIndicator by using the following command to start the application:

    env XDG_CURRENT_DESKTOP=unity nitroshare

Before you run that command though, I would suggest making sure that NitroShare is not still running:

    killall -q nitroshare

**Comment by jpfleury** [comment]
Thanks a lot for this very quick answer. Your workaround works great.

**Comment by rtud** [comment]
Have the same issue w/ Elementary OS Freya, and your quickfix worked like a charm, thanks.

**Comment by thermatk** [comment]
Fixed upstream: https://bugreports.qt.io/browse/QTBUG-43859
Already working great in Arch with the latest updates

**Comment by nathan-osman** [comment]
Great, thanks for the update guys. I'll close this issue then since it appears to be an upstream problem and a fix is on the works.

**Comment by dubst3pp4** [comment]
Seems not to work in elementray OS 0.3. Can someone give me an hint what @rtud did to solve the problem?

**Comment by nathan-osman** [comment]
I've released a new version (0.3.1) which includes code that detects the desktop environment and selects the appropriate system tray / indicator class. I tested on ElementaryOS 0.3.2 and the application works perfectly now.

**Comment by dubst3pp4** [comment]
Works perfect, thanks! :-)
