### ISSUE TITLE
Improve opening ux - users not recognizing tray only use.

### ISSUE THREAD

**Issue by mateosalta** [nitroshare/nitroshare-desktop#39]
So I showed NitroShare to some friends, program was preinstalled.
User launched the program twice without noticing it was running in the tray.

So I'm thinking 
1. On first launch show the transfers window
 - If you close/min you can still use the tray
 - Show buttons to transfer files within the transfers window
2.  If you turn on launch on startup - just display the icon on system startup
 - If someone tries to launch second instance - show transfer window

In general I like the first run splash on install, but if a user sits down at a computer lab environment where the program would likely be preinstalled, this should help.

![screenshot from 2015-04-19 08 26 19](https://cloud.githubusercontent.com/assets/1965279/7219628/ff937d0a-e66d-11e4-9581-28e39ba9a0dd.png)

**Comment by nathan-osman** [comment]
This seems like a good idea for the next couple of minor versions. Eventually, the plan is to move to a QML interface for the main window, which will include equivalent buttons as well.

As for multiple instances, that should be fixed too.

**Comment by nathan-osman** [comment]
I've added the two buttons now:

![](http://i.stack.imgur.com/dq8oj.png)

**Comment by mateosalta** [comment]
nice!
