### ISSUE TITLE
Settings dialog is needed

### ISSUE THREAD

**Issue by nathan-osman** [nitroshare/nitroshare-desktop#4]
Currently, there is no way to adjust settings through a graphical interface. (Advanced users can open `~/.config/Nathan Osman/NitroShare.conf` and edit values directly.) The previous version of NitroShare included a settings dialog that grouped settings in a tabbed interface.

Ideally, the settings dialog would use either a row of tabs or a listbox along the left side of the window (similar to what VLC has done) to group settings. The list of configurable settings can be found in `src/util/settings.h`.

When opened, the dialog should use `Settings::get()` to retrieve the current value for each setting. If the user accepts the dialog (clicks "OK"), the settings can be saved with `Settings::set()`. (This function will automatically notify the other classes which values have changed.)

**Comment by nathan-osman** [comment]
One of the settings that will need special handling is the "start NitroShare at startup" setting. This is platform specific:

- On Windows, this involves adding a key to `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`
- On Linux, this involves adding a `.desktop` file to `~/.config/autostart`
- I have no idea what this involves on OS X :stuck_out_tongue:

**Comment by mateosalta** [comment]
it was a `com.nitroshare.launcher.plist` file on OSX, in `~/Library/LaunchAgents` https://github.com/nathan-osman/NitroShare-Mac/commit/895966a3ff67a4112415619ec0180c20d6de50fd

**Comment by mateosalta** [comment]
that or the mac dock has load at startup built into it on right click on every program... so not really needed to implement.

**Comment by nathan-osman** [comment]
Perfect - if the dock offers that feature, there's no need to implement it ourselves. That just leaves Windows and Linux. And I already have the code for getting it running on those platforms.

**Comment by nathan-osman** [comment]
The ranges for the settings are as follows:

Setting | Minimum | Maximum | Default | Comments
---------|------|------|-------|------
Broadcast Interval | 1 second | ∞ | 5 seconds | time between sending broadcast packets
Broadcast Port | 1 | 65535 | 40816 | port used for sending broadcast packets
Broadcast Timeout | 1 second | ∞ | 30 seconds | if no ping is received by a device after this amount of time elapses, it is considered offline
Device Name | n/a | n/a | _hostname_ | descriptive name shown to other devices
Device UUID | n/a | n/a | _randomly generated_ | used to uniquely identify the device
Transfer Buffer | 1,024 bytes (1 KiB) | 1,048,576 bytes (1 MiB) | 65,536 bytes (64 KiB) | size of buffer used for sending file data
Transfer Directory | n/a | n/a | _desktop_ | location where received files are stored
Transfer Port | 1 | 65535 | 40818 | port used for sending transfers
Transfer Timeout | - | - | 30 seconds | _no longer used_
Update Interval | 1 hour | 48 hours (2 days) | 24 hours (1 day) | time between successive update checks

**Comment by nathan-osman** [comment]
This was implemented with commit eb44f0b.
