### ISSUE TITLE
Custom graphics/custom installer for Windows?

### ISSUE THREAD

**Issue by RPiAwesomeness** [nitroshare/nitroshare-desktop#40]
I just installed NitroShare on a Windows 7 PC and realized that the installer just has that default blue look to it.

Now, I know this isn't a massive issue, but I think it would look much nicer if you had either a custom graphic instead of the default blue computer image, or a custom installer with custom graphics.

Just an idea!

**Comment by nathan-osman** [comment]
If I have time, I'll fix this in the next release.
