### ISSUE TITLE
Windows client to Windows client transfer of an LNK file fails.

### ISSUE THREAD

**Issue by FabrizioMarana** [nitroshare/nitroshare-desktop#43]
Source OS: Windows Vista 
Target OS: Windows 8.1

Symptom:
When sending  the "Pictures" directory from a Vista client whose default directory setting is "c:\users\DummyUser\"  to an 8.1 client with c:\Users\DummyUser\ as its default directory setting, the source directory (on Vista) contains a link to c:\Users\Public\Pictures\Examples\.  Though the .LNK file exists, the linked-to directory doesn't.
 
The transfer creates all subdirectories on the target, but fails with an error on both clients as the .LNK file is reached and stops instead of giving a warning and continuing the other files.

Work-around:
Set the directory setting on both clients to c:\users\DummyUser\Pictures\ and send all files first and then all directories one by one instead of the entire "Pictures" directory.

**Comment by nathan-osman** [comment]
I'm wondering if the proper solution to this problem doesn't involve dealing with the `.lnk` files at all and instead involves properly skipping files that can't be read and displaying some sort of summary afterward describing what could and could not be transferred.

**Comment by FabrizioMarana** [comment]
That would be good!

Or have Green, orange and red: Info, warn, error and display while it's
happening... (Now, that would be *great*!) Just don't spend an hour on
it...

Fabrizio

**Comment by nathan-osman** [comment]
I'm having trouble reproducing this between my Windows 10 box and a Windows 7 VM. I think the easiest thing to do would be to have NitroShare skip over any such files.

**Comment by FabrizioMarana** [comment]
Yes, good idea!

On Monday, June 22, 2015, Nathan Osman <notifications@github.com> wrote:
> I'm wondering if the proper solution to this problem doesn't involve
dealing with the .lnk files at all and instead involves properly skipping
files that can't be read and displaying some sort of summary afterward
describing what could and could not be transferred.

**Comment by nathan-osman** [comment]
The files are now skipped. In the next release, I'll take a look at having the links actually transferred as links. But for now, this will do. The change should show up in the PPA sometime tomorrow.
