### ISSUE TITLE
Retina Support

### ISSUE THREAD

**Issue by johnhamelink** [nitroshare/nitroshare-desktop#46]
It would be nice for nitroshare to receive retina support - especially the icon as it's always in the statusbar.

**Comment by mateosalta** [comment]
can you take screen shots of affected items, this might help.
I'm guessing the icon would be an easy fix - was anything else off? I'm not sure any of us have a retina device.

**Comment by nathan-osman** [comment]
Which platform? NitroShare uses SVG icons in nearly all cases. The only exception to this is on Linux when icons matching the current theme and panel size are available.

**Comment by mateosalta** [comment]
I'm guessing he meant on OSX because of the use of apples marketing term for hidpi screens

**Comment by nathan-osman** [comment]
Is there a way to force OS X to use a much higher DPI even on a smaller display?

**Comment by mateosalta** [comment]
huh, maybe? http://www.resolutiontab.com/ - look at their "Learn more" note

**Comment by johnhamelink** [comment]
I'm using nitroshare to share files between my macbook pro and my Arch linux box. It looks great on Linux, but on my retina macbook pro it looks very pixelated, which is common amongst applications which haven't been optimised for retina (Hidpi) displays.

The icon compared to others on my statusbar:
<img width="818" alt="screen shot 2015-09-26 at 11 43 28" src="https://cloud.githubusercontent.com/assets/101739/10117102/d72cc6e2-6443-11e5-937c-aabd424f8e5d.png">

The settings window compared to the text I'm writing on chrome:
<img width="952" alt="screen shot 2015-09-26 at 11 44 17" src="https://cloud.githubusercontent.com/assets/101739/10117108/ff313cb8-6443-11e5-901d-fe6c12c980a1.png">

**Comment by johnhamelink** [comment]
Also, a quick google shows this blog post which might be of help: http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/

**Comment by mateosalta** [comment]
I managed to enable a hidpi mode on my 17" 2009 macbook pro - and confirm that everything looks fuzzy - I'll try out some of those fixes in a moment here.
