### ISSUE TITLE
Requires uninstalation of google-chrome-stable

### ISSUE THREAD

**Issue by kpchand** [nitroshare/nitroshare-desktop#47]
I am on Linux Mint using Google-Chrome Version 46.0.2490.71  and while installing Nitroshare 0.3.0, it requires the uninstallation of google-chrome-stable and vice versa. Possible reason?

**Comment by nathan-osman** [comment]
Are you installing via PPA or by using a binary package?

**Comment by kpchand** [comment]
I am installing via DEB Package (i386).

**Comment by kpchand** [comment]
Later I installed via PPA and it seems to be working fine now(no uninstallations), seems to be that i386 package is having some issues on my 64 bit computer.

**Comment by nathan-osman** [comment]
Glad to hear you were able to get it working.

I'll see if I can reproduce this on one of my virtual machines and then see which package is causing the problem. I'm not sure I would be able to fix it though. The Debian packages only include a minimal set of dependencies and none of them can easily be dropped.
