### ISSUE TITLE
nitroshare android support 

### ISSUE THREAD

**Issue by shivarajnaidu** [nitroshare/nitroshare-desktop#48]
what about nitroshare for Android?

**Comment by nathan-osman** [comment]
This is planned.

**Comment by enr00ted** [comment]
This is a must :)

**Comment by maz-1** [comment]
Meanwhile you can try out dukto, which is available on almost all desktop and mobile platforms : -)

**Comment by beerisgood** [comment]
How is the status for a android version?

A F-Droid version would be awesome!

Dukto doesn't works nice and give a lot of errors.

**Comment by nathan-osman** [comment]
This is currently in progress. I'm hoping to have it ready when the next release of NitroShare comes out. Unfortunately, due to the large amount of work that this requires, it may be a few months before it is complete.

**Comment by beerisgood** [comment]
*push*

**Comment by techtonik** [comment]
@nathan-osman maybe create

* [ ] a roadmap for
* [ ] contributors
* [ ] ?

**Comment by nathan-osman** [comment]
I am excited to announce that this issue will be closed because NitroShare for Android is finally here.

The application supports Android => Android transfers and the desktop client will be updated shortly to allow Android => desktop transfers. In the meantime, anyone who wants to help test the application can do so by sending me their Gmail address (you can email me at `nathan@quickmediasolutions.com`), which I will use to add you to the closed alpha on the Play Store.

**Comment by techtonik** [comment]
techtonik@gmail.com please. Can I just download .apk to install manually?

**Comment by nathan-osman** [comment]
Providing an APK at this point just isn't feasible since the app is being updated on an almost daily basis.

**Comment by techtonik** [comment]
Maybe https://f-droid.org/ then?

**Comment by nathan-osman** [comment]
I wouldn't mind seeing this in F-Droid but it will need a lot more work before it is considered stable enough to be added.

**Comment by kevincox** [comment]
FWIW the sources are here https://github.com/nitroshare/nitroshare-android so you can always build it yourself if you are dying to try it. 

I wouldn't expect Nathan to put too much effort into packaging and distribution until it is released, whatever is most convenient for him makes sense for the alpha. You can see that he is putting in a huge amount of development work and I wouldn't want that to slow down.
