### ISSUE TITLE
Ability to not autoaccept files and folders - feature reuqest

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [nitroshare/nitroshare-desktop#53]
Currently it autoaccepts all files and folders, this may be unwanted due to it potentially being a security risk and clogging things up.

So I think that it would be really good if autoaccepting of files and folders was be off by default (but to have it possible to enable it in the settings for all (except the devices you have chosen to block), or specific devices) and for it instead to ask you about every file and folder that is available for transfer to your machine (and to give you the options "Accept", "Reject", and "Reject and Block device permanently").

**Comment by nathan-osman** [comment]
This is now partly implemented. You can now choose not to receive files on a particular machine. You will still be able to send files to that machine.
