### ISSUE TITLE
Secure connection - feature request

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [nitroshare/nitroshare-desktop#55]
I think that it would be really good if NitroShare used a secure encrypted connection to transfer files as well as using digital signatures to verify that the contents has in no way been altered during transit (this would all be done in the background without need of user interaction, and the digital signatures bit would be configurable in the advanced settings).

**Comment by nathan-osman** [comment]
I'm going to stretch things and try to get this into the next release (0.3.2). It will be very straightforward:

- a CA certificate is required
- a certificate signed by the CA and private key are required by each client
- during transfers the clients will verify the certificate presented by the remote end of the connection to ensure it is signed by the CA

Yes, this is a bit of work to configure, but it will work for now until a more user-friendly design is created.
