### ISSUE TITLE
Have some sort of changelog accessible through NitroShare - feature request

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [nitroshare/nitroshare-desktop#57]
I think that it would be really good if in the GUI somewhere there was a changelog for each version (also displaying changes for previous versions probably in standard changelog format). So perhaps in the "About" section there should be a button called "Changes" or "Changelog" or something which should take you to it. Or even if not in the GUI, you could have a Terminal option which could display the changelog with a command such as "nitroshare --changelog".

**Comment by nathan-osman** [comment]
The Debian packaging contains a changelog: https://github.com/nitroshare/nitroshare-desktop-debian/blob/master/changelog

**Comment by SeventhSonOfASeventhSon** [comment]
Yes, however it is not very convenient to have to download the source or go to github every time one wants to view the changelog, and as it's in a PPA there is no easy way through APT to view the changelog. So at least provide a link in the about section to the changelog on github, because some end users may not even know of github, but will want to know what has changed.

**Comment by techtonik** [comment]
:+1: because I don't see any changelog on GitHub either..

**Comment by nathan-osman** [comment]
The changelog for each release can be found here: https://github.com/nitroshare/nitroshare-desktop/releases
