### ISSUE TITLE
Required unity leaves nitroshare unbuildable on other Linuxes than Ubuntu

### ISSUE THREAD

**Issue by glitsj16** [nitroshare/nitroshare-desktop#61]
CMakeLists.txt currently has a hard-coded dependency on unity:
line 33 --> pkg_check_modules(UNITY REQUIRED unity)
This stops building nitroshare on any other Linux distro that doesn't offer unity (tested on Arch Linux). Dropping this to 'pkg_check_modules(UNITY unity)' still keeps unity integration intact on Ubuntu (tested on 16.04 dev) while enabling builds on other Linuxes. Might you consider relaxing this requirement?

**Comment by nathan-osman** [comment]
Yes, the inclusion of `REQUIRED` was an oversight on my part. I'll fix this when I'm back in front of a computer this evening.
