### ISSUE TITLE
Intro screen doesn't display correctly on Retina displays

### ISSUE THREAD

**Issue by nathan-osman** [nitroshare/nitroshare-desktop#62]
When the intro screen is displayed on a Retina-enabled display, it appears pixelated.

**Comment by mateosalta** [comment]
just the graphics?

**Comment by nathan-osman** [comment]
Yeah, the splash screen is just a single image. It appears the same logical size when run on a Retina display which, of course, isn't a 1:1 correspondence with the physical pixels on the display.

**Comment by mateosalta** [comment]
ah, so a double the size of the image thing?

**Comment by nathan-osman** [comment]
Basically, yes. Practically, I'd like to redo the image as an SVG.
