### ISSUE TITLE
Protocol description

### ISSUE THREAD

**Issue by techtonik** [nitroshare/nitroshare-desktop#63]
It might help to develop other clients (Android) if the protocol was somehow described.

**Comment by nathan-osman** [comment]
Good idea. I am planning to start working on the Android client next week but describing the protocol would still be useful. I'll try to take care of that this evening.

**Comment by techtonik** [comment]
Awesome! I may be able to create a Python server for that then.

**Comment by nathan-osman** [comment]
I've added the description to the README. Please let me know if anything needs further clarification.

**Comment by techtonik** [comment]
Nice. It lacks only discovery phase.

**Comment by techtonik** [comment]
The rest is in #66.
