### ISSUE TITLE
Application should not show in OS X dock

### ISSUE THREAD

**Issue by nathan-osman** [nitroshare/nitroshare-desktop#64]
The application appears in the OS X dock when run on that platform. This does't make much sense since all interaction with the application is done through the tray icon.

Apparently, removing the application from the dock involves adding the `LSUIElement` key to the `Info.plist` file.

**Comment by mateosalta** [comment]
On the .2, I added a setting to enable/disable, and added all the commands to the dock - if you are going to switch to a more window based usage of the program, I suggest keeping it showing in the dock, and transferring functions to the global menu - mac applications make more sense that way (also given the icon likes to disappear sometimes, bug and theme issue)

**Comment by nathan-osman** [comment]
Oh yeah, I forgot about that. Does the latest version still have the disappearing tray icon issue? (I kind of though I had fixed that.)

**Comment by mateosalta** [comment]
I'll have to test, I also was using a theming application that turned the bar dark
