### ISSUE TITLE
Document discovery protocol

### ISSUE THREAD

**Issue by techtonik** [nitroshare/nitroshare-desktop#66]
What is the discovery protocol that Nitroshare uses? I think I can try reversing it or reading through the C++, but it would be nice to see this officially documented to ensure it won't change.

**Comment by techtonik** [comment]
I see broadcast UDP packets to local LAN 192.168.1.255:40818 with the following contents:

{"name":"Arachnoid","operating_system":"windows","port":"40818","uuid":"{60e37400-5cc3-10c9-931c-2633ac56fbcc}"}

**Comment by techtonik** [comment]
Not clear how "uuid" is generated and what are possible values for "operating_system" part.

**Comment by hobarrera** [comment]
It can be any of `window`, `osx`, `linux` or `unknown` [[source]](https://github.com/nitroshare/nitroshare-desktop/blob/cadf6217ab4111d493bcc41599937964bdcebb7b/src/util/platform.cpp#L81).

**Comment by nathan-osman** [comment]
UUID is generated by [this class](http://doc.qt.io/qt-5/quuid.html) (on [this line](https://github.com/nitroshare/nitroshare-desktop/blob/cadf6217ab4111d493bcc41599937964bdcebb7b/src/settings/settings.cpp#L54)). It is generated the first time NitroShare runs and should not be change since it uniquely identifies the client.

**Comment by techtonik** [comment]
I see. I implemented Nitroshare discovery in Python. https://bitbucket.org/techtonik/discovery/src/74572355ab123afcc24cd3346d321fd76e76d158/interface/net/udp/nitroshare.py?at=default&fileviewer=file-view-default The code is in public domain, so if anybody needs it (to detect Nitroshare, for example), feel free. I actually planned to implement "sendfile" command to upload files from command line, but it looks like it doesn't happen.

**Comment by techtonik** [comment]
It looks like it is manageable to do upload capability synchronously without the need of Twisted etc.

BTW, how about moving https://github.com/nitroshare/nitroshare-desktop#protocol-description into its own doc and add discovery chapter into it? That will make this information more easily searchable.

**Comment by nathan-osman** [comment]
Sorry for the delay. I finally got around to doing this:  
https://github.com/nitroshare/nitroshare-desktop/wiki/Broadcast-Protocol

**Comment by techtonik** [comment]
Awesome. Updated my Python discovery code to report listening port and interface https://bitbucket.org/techtonik/discovery/src/a26d90afe19e8c28dc46e01ffa4d4e13e1992902/interface/net/udp/nitroshare.py?at=default&fileviewer=file-view-default

**Comment by techtonik** [comment]
It worth mentioning that 0.4+ may employ different discovery protocol - https://github.com/nitroshare/nitroshare-desktop/issues/68#issuecomment-231563795

**Comment by nathan-osman** [comment]
I will update the wiki with the information when things are ready. It is also worth mentioning that 0.4 will continue to support the old method (IPv4 broadcast) through a plugin that will be enabled by default.
