### ISSUE TITLE
Default sync folder should not be "Desktop"

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [nitroshare/nitroshare-desktop#69]
It just feels rather strange for it to be the "Desktop", plus people may have all sorts of things on their Desktop such as links to personal files, personal files, etc already so I think that in the home folder of the user it should just create a folder called something like "NitroShare Sync Folder" and use that instead, or not set a folder by default. But I think that the Desktop is a really unusual and bad idea, plus some people by default have their Desktop disabled and may not all know or want to enable it (it is disabled by default on Ubuntu GNOME for instance).

**Comment by nathan-osman** [comment]
This is tricky because of the way things are organized on different platforms. On Linux, the home directory (`~/NitroShare`) would be an ideal choice but this would not work well on Windows and OS X. `~/Documents` seems like a logical choice but not a semantically correct one. `~/Downloads` actually seems like a reasonable alternative. What do you think?

**Comment by FabrizioMarana** [comment]
Downloads looks like a good compromise to me...

:-)

Fabby

**Comment by SeventhSonOfASeventhSon** [comment]
@nathan-osman, No, I think Downloads is still a bad idea because it's firstly a little bit strange, but if you think about it, people could have all sorts of things in that folder which they won't want to share for instance someone could even have downloaded sensitive bank connected information and won't realise that it gets sent to everyone when they install NitroShare, they really could have all sorts of things, even malware they didn't realise they downloaded... And if people don't know how to change the default folder, they might just remove NitroShare because they won't want everything they download to be sent to everyone.

Can NitroShare just determine which OS is on the system and do differently for each one?

**Comment by nathan-osman** [comment]
That doesn't make any sense. Downloads would be used for _receiving_ files, not sending them.

**Comment by SeventhSonOfASeventhSon** [comment]
Oh, so it doesn't have a system of syncing one folder with another like most syncing systems do? Haven't used it in a while so maybe that's why I didn't remember... But do people just manually select files to send then? If that's how it works, then the Downloads folder I think would be a reasonable compromise for where to store received files, though perhaps there should be a special NitroShare folder in there so that the user doesn't mix all the received stuff through NS with their other downloads?

**Comment by nathan-osman** [comment]
Yeah, that's what I intended. A directory within "Downloads".

**Comment by mateosalta** [comment]
Yes, things are not automatically sent/synced - the user chooes files to send one time.

I like the idea of Downloads/NitroShare

**Comment by nathan-osman** [comment]
Oh hang on, I just realized I forgot to use a directory within Downloads.
