### ISSUE TITLE
RPC interface for sending files and directories

### ISSUE THREAD

**Issue by nathan-osman** [nitroshare/nitroshare-desktop#7]
The previous version of NitroShare included an RPC interface for sending files and directories across the network. This was removed since it depended on a third-party library. When implementing this feature again, it should be done as follows:

- The interface should be a very basic HTTP server
- It should only listen on `127.0.0.1`
- Request method should be POST and consist of JSON data

For example, sending a `POST` request to `/api/send` with the following request body should initiate the appropriate transfer:

    { "files": ["file1.jpg", "file2.jpg"] }

**Comment by nathan-osman** [comment]
**Update:** this is nearing completion, in the form of a new Qt library named [QHttpEngine](https://github.com/nitroshare/qhttpengine). Once finished, QHttpEngine will allow NitroShare to expose an API allowing local scripts and tools to interact with the application.

**Comment by techtonik** [comment]
What would be the port for that stuff?

**Comment by nathan-osman** [comment]
I want to stress that the new API is **really** early in development and may not work correctly. Currently, it works something like this:

- when NitroShare starts, it creates a file `~/.NitroShare` with JSON data containing the local port and a special token

- to send files, send a POST request to `http://localhost:[port]/sendItems` with the `X-Auth-Token` header set to the token from the file

- the POST payload should be a JSON request of the following form:

        {
            "items": [
                "file1.txt",
                "file2.txt",
                ...
            ]
        }

If all goes well, the "Select Device" dialog will appear to let the user decide where to send those files.

**Comment by techtonik** [comment]
And where it will those files?

**Comment by nathan-osman** [comment]
You can take a look at this example to get an idea of how it works:

https://gist.github.com/nathan-osman/6de0675bdcf187fc2204c6defdde883f

**Comment by techtonik** [comment]
I still don't understand how Nitroshare find those files?

**Comment by nathan-osman** [comment]
The API expects absolute paths to files on the local filesystem.

**Comment by techtonik** [comment]
But those doesn't look like absolute. Are they in `/`?
```
  "items": [
        "file1.txt",
        "file2.txt",
        ...
```
