### ISSUE TITLE
French  translation

### ISSUE THREAD

**Issue by david-geiger** [nitroshare/nitroshare-desktop#78]
Hi,

Would it be possible to provide a French .ts file so I can translate it?

Thanks in advance!

**Comment by nathan-osman** [comment]
The English .ts file is located at `src/data/ts/en.ts`. The easiest way to perform the translation may be to open this file and select French as the target language:

![](http://i.stack.imgur.com/uoXHv.png)

Then go to File -> Save As and name it "fr.ts" (adding the region to the filename if applicable). Although the .ts file can be used on its own, if you download all of the source code and open the .ts file in there, Qt Linguist will display the context of each translation string:

![](http://i.stack.imgur.com/UkIEn.png)

Please let me know if you need any help.
