### ISSUE TITLE
Nemo extension dependency in PPA wrong

### ISSUE THREAD

**Issue by hotice** [nitroshare/nitroshare-desktop#83]
The nitroshare-nemo package (0.3.3) available in the NitroShare PPA is not installable because it depends on "nemo-python", while the actual package name is "python-nemo", as can be seen here: http://packages.linuxmint.com/search.php?keyword=python-nemo&release=any&section=any

**Comment by nathan-osman** [comment]
In Debian, the package is named"nemo-python: https://packages.debian.org/search?keywords=nemo-python - I didn't realize Mint was providing their own package.

**Comment by hotice** [comment]
You can just use "python-nemo | nemo-python" as the dependency to satisfy both (Linux Mint and Debian; Ubuntu doesn't have this package yet, though in PPAs it's used as in Mint).

**Comment by nathan-osman** [comment]
Yup, I'll get the packaging updated. It should be noted that the "nemo-python" package is available in Yakkety: http://packages.ubuntu.com/yakkety/nemo-python

**Comment by nathan-osman** [comment]
New builds have been dispatched to the PPA and should complete within an hour or so.

**Comment by hotice** [comment]
Thank you!
