### ISSUE TITLE
OpenGL requirement

### ISSUE THREAD

**Issue by techtonik** [nitroshare/nitroshare-desktop#85]
I just noticed `opengl32sw.dll` in NitroShare installation dir. Why?

**Comment by techtonik** [comment]
Also `d3dcompiler_47.dll`, `libEGL.dll` and `libGLESV2.dll`, which points to [ANGLE](https://chromium.googlesource.com/angle/angle/+/master/README.md).

**Comment by nathan-osman** [comment]
Qt uses OpenGL and to simplify implantation on Windows, they use ANGLE to translate the calls to DirectX.

**Comment by techtonik** [comment]
IIRC Qt uses native graphics API for rendering Windows etc. What API exactly requires ANGLE and where it is used to NitroShare?

**Comment by nathan-osman** [comment]
I'm not entirely sure where it is used, but OpenGL / ANGLE is automatically deployed by `windeployqt`, which the CMake scripts use.

**Comment by techtonik** [comment]
I can't find which Qt calls need ANGLE, but this thread - https://stackoverflow.com/questions/17736229/do-i-have-to-include-all-these-qt-dlls-with-my-application says that it is possible to get rid of extra dependencies with static linking.

**Comment by nathan-osman** [comment]
Looks like this might be solved with Qt 5.8: http://blog.qt.io/blog/2016/08/18/introducing-the-qt-lite-project-qt-for-any-platform-any-thing-any-size/

**Comment by nathan-osman** [comment]
I'm closing this since the latest release switched to software rendering and no longer needs the ANGLE / OpenGL runtime.
