### ISSUE TITLE
Doesn't exit after "port busy" error

### ISSUE THREAD

**Issue by techtonik** [nitroshare/nitroshare-desktop#86]
NitroShare allows multiple instances to run even if it failed to bind needed port. Seems like a bug to me. I expect it to exit if port is busy.

![mutex](https://cloud.githubusercontent.com/assets/515889/16849789/d4002d04-4a04-11e6-9ec0-8215703e1d7f.png)

**Comment by nathan-osman** [comment]
The code that attempts to listen on a specific port is invoked both when the application starts and when the setting is changed. The code would need to be modified in such a way that an error during program initialization is handled separately. The next version is going to introduce some drastic changes to the codebase so this problem may end up going away on its own.
