### ISSUE TITLE
Failure to start on Wayland / Fedora 24

### ISSUE THREAD

**Issue by techtonik** [nitroshare/nitroshare-desktop#95]
```
$ nitroshare
QXcbConnection: Could not connect to display wayland-0
Aborted (core dumped)
```

**Comment by nathan-osman** [comment]
I'll have to take a closer look but this sounds like an issue with Qt. Do other Qt 5 applications run without problems?

**Comment by techtonik** [comment]
Any hints which ones to try?

**Comment by nathan-osman** [comment]
Some of the other Qt 5 applications available on Fedora include `kamera`, `texstudio`, `twinkle`, and `marble`.

**Comment by mateosalta** [comment]
hm, maybe? https://bugreports.qt.io/browse/QTBUG-28819

**Comment by techtonik** [comment]
Fedora 27 doesn't crash anymore, however tray icon is not visible, which is another bug.
